coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 0%
        informational: false
        if_ci_failed: error

ignore:
  - tests

fixes:
  - "ansible_collections/community/healthchecksio/::"
