name: sanity
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  sanity:
    name: Sanity (Ⓐ$${{ matrix.ansible }})
    strategy:
      matrix:
        include:
          - ansible: stable-2.10
            python-version: '3.9'
          - ansible: stable-2.11
            python-version: '3.9'
          - ansible: stable-2.12
            python-version: '3.9'
          - ansible: stable-2.13
            python-version: '3.9'
          - ansible: devel
            python-version: '3.12'
    runs-on: ubuntu-latest
    steps:
      - name: Perform testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: ${{ matrix.ansible }}
          # pre-test-cmd:
          python-version: ${{ matrix.python-version }}
          # target-python-version:
          testing-type: sanity
          # test-deps:
